version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecomdb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - guitardbnetwork

  guitardb:
    image: guitardb
    container_name: guitardb_1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ecomdb
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - guitardbnetwork

  angular:
    build:
      context: ./guitar
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:80"
    networks:
      - guitardbnetwork

networks:
  guitardbnetwork:
    driver: bridge
